name: ci
on: 
  push:
    paths-ignore:
      - 'README.md'

permissions:
  contents: read      
        
jobs:
  build:   
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: erlef/setup-beam@v1
      - run: make compile

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - run: make ct
